### ISSUE TITLE
How to generate target from double value difficulty?

### ISSUE THREAD

**Issue by nsiatras** [nicehash/nhethpool#1]
Hello,

On your stratum manual you mention the following:

"First item of params array is **difficulty in double data type**. Conversion
between difficulty and target is done the same way as with Bitcoin; 
difficulty of 1 is transformed to target being in HEX:
00000000ffff0000000000000000000000000000000000000000000000000000"

How can someone convert the double value to that 64 bit long hex ? 
I am searching for this algorithm on bitcoin forums and websites but there is no info about that.
Do you have any code for that in some high level language like Java, C# etc.. ?

Thank you

**Comment by nicehashdev** [comment]
Calling this function: https://github.com/nicehash/nhethpool/blob/master/sharecheck/ethereum.c#L452

Will create HEX null terminated string out of provided double value.

You can also call it from C#: https://github.com/nicehash/nhethpool/blob/master/nhethpool/ShareCheckWrapper.cs#L44

**Comment by nsiatras** [comment]
Hello,

I found the solution and I uploaded a small Java code on my blog.
https://codemammoth.blogspot.gr/2016/10/bitcoin-target-from-difficulty.html

Thank you :)
